ENT.Base 		= "npc_vj_creature_base"
ENT.Type 		= "ai"
ENT.PrintName 		= "npc_vj_aahw_mag_agent_torture"
ENT.Author 		= "noob_dev2323"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Category		= "madness combat remake"
