--TODO list

--nevada map
--bullet defece
--surfaceprop 
--make npc avoid crossrair
--view model weapons
--mask damege
--zeds
--player models
--flex fire effect
--jettpack npc
--grunt_suicidal_bomber sound
--zombie eat corpse
--foot step