--TODO list

--nevada map
--bullet defece
--surfaceprop 
--mask damege
--zeds
--player models
--flex fire effect
--jettpack npc
--grunt_suicidal_bomber sound
--zombie eat corpse
--foot step
--text on dead ragdoll
--botle melee
--zombie range atack
--hats